### ISSUE TITLE
the weather

### ISSUE THREAD

**Issue by dbrunson** [OSU-HPCC/hpc-novice-first-draft#2]
I love what's coming forth from this!  I do have a nit to pick with the weather example here: https://github.com/OSU-HPCC/hpc-novice-first-draft/blob/master/modules/what-is-hpc.md 

Since we want "realistic" examples, we may want to work on that one.  Maybe predicting the chance of storms in a few days time might be a better example than predicting the temperature in a year (which is impossible no matter how big the supercomputer is.)

**Comment by pdoehle** [comment]
@dbrunson Yeah, I knew we might need to revisit that example, but I wanted to get something out on the page. I'm not so familiar with weather stuff. Is there an example we can use that would show how the problem is serial and not aided by a supercomputer?

**Comment by pdoehle** [comment]
A bit of clarification. I actually modified the chemistry example from one of the papers so it's realistic. Do we know a weather person who could give a realistic weather example?

**Comment by dbrunson** [comment]
Maybe focus on developing the work with Matt and Raj first and just leave something like "fill in example here" in the current document.
